version: '3'

services:
  osmo_base_station:
    build:
      context: ./osmo_base_station
      dockerfile: Dockerfile
    container_name: osmo_base_station
    volumes:
      - ./config/osmo_base_station:/data:rw
    networks:
      - osmocom-net
    ports:
      - "4242:4242"
      - "4241:4241"
      - "3003:3003"
      - "3002:3002"

networks:
  osmocom-net:
    driver: bridge
