services:
  hss:
    build: ./hss
    container_name: hss
    volumes:
      - ./hss/config.yaml:/pyhss/config.yaml
    ports:
      - "8180:8080" # REST API
      - "3868:3868" # Diameter
    networks:
      mobile-net:
        aliases:
          - hss.mnc001.mcc001.3gppnetwork.org

  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mobile-net

networks:
  mobile-net:
