services:
  pyhss:
    build: .
    container_name: pyhss
    volumes:
      - ./config.yaml:/pyhss/config.yaml
    ports:
      - "8180:8080" # REST API
      - "3868:3868" # Diameter
    depends_on:
      - db
