services:
  routr:
    image: fonoster/routr-one:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      EXTERNAL_ADDRS: ${DOCKER_HOST_ADDRESS}
      DATABASE_URL: ${DATABASE_URL}
      RTPENGINE_HOST: rtpengine
    ports:
      - 51908:51908
      - 5060:5060/udp
      - 5060:5060/tcp
      - 5062:5062/tcp
      - 5062:5062/udp
  rtpengine:
    image: fonoster/rtpengine:latest
    ports:
      - 22222:22222/udp
      - 10000-10100:10000-10100/udp
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PUBLIC_IP: ${DOCKER_HOST_ADDRESS}
      PORT_MIN: 10000
      PORT_MAX: 10100
  simplephone:
    image: psanders/simplephone:latest
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
