services:
  routr:
    image: fonoster/routr-one:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      EXTERNAL_ADDRS: ${DOCKER_HOST_ADDRESS}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 51908:51908
      - 5060:5060/udp
      - 5060:5060/tcp
