db_uri: mongodb://db.samcom/open5gs

logger:
  file:
    path: /var/log/open5gs/pcf.log

global:

pcf:
  sbi:
    server:
      - address: pcf.samcom
        port: 80
    client:
      nrf:
        - uri: http://nrf.samcom:80
