db_uri: mongodb://db.samcom/open5gs

logger:
  file:
    path: var/log/open5gs/udr.log

global:

udr:
  sbi:
    server:
      - address: udr.samcom
        port: 80
    client:
      nrf:
        - uri: http://nrf.samcom:80
